In [1]:
x, y = zip(['a', 1], ['b', 2], ['c', 3])

In [2]:
print(x)

('a', 'b', 'c')


In [3]:
print(y)

(1, 2, 3)


In [4]:
sequences = [['a', 1], ['b', 2], ['c', 3]]

In [5]:
x, y = zip(*sequences)

In [6]:
print(x)

('a', 'b', 'c')


In [7]:
print(y)

(1, 2, 3)


In [8]:
import pandas as pd

In [9]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

In [10]:
df = pd.DataFrame(values, columns=columns)

In [11]:
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [16]:
x=df['메일 본문']
y=df['스팸 메일 유무']

In [17]:
print(x)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object


In [19]:
print(y)

0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


In [20]:
import numpy as np

In [21]:
ar = np.arange(0,16).reshape((4,4))

In [22]:
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
x = ar[:, :3]

In [24]:
print(x)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [25]:
y = ar[:, 3]

In [26]:
print(y)

[ 3  7 11 15]


In [27]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split

In [34]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [35]:
print(x)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [36]:
print(list(y))

[0, 1, 2, 3, 4]


In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)

In [39]:
print(X_train)

[[2 3]
 [4 5]
 [6 7]]


In [40]:
print(X_test)

[[8 9]
 [0 1]]


In [41]:
print(y_train)

[1, 2, 3]


In [42]:
print(y_test)

[4, 0]


In [43]:
import numpy as np
X, y = np.arange(0,24).reshape((12,2)), range(12)

In [44]:
print(X)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [45]:
print(list(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [46]:
n_of_train = int(len(x) * 0.8)
n_of_test = int(len(X) - n_of_train)

In [47]:
print(n_of_train)

3


In [48]:
print(n_of_test)

9


In [49]:
X_test = X[n_of_train:]
y_test = y[n_of_train:]
X_train = X[:n_of_train]
y_train = y[:n_of_train]

In [50]:
print(X_test)

[[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [51]:
print(list(y_test))

[3, 4, 5, 6, 7, 8, 9, 10, 11]
